In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix

In [2]:
df=pd.read_csv("data.csv")

In [3]:
df.sample(4)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
78   8610862         M        20.18         23.97          143.70     1245.0   
484   912600         B        15.73         11.28          102.80      747.2   
349   899147         B        11.95         14.96           77.23      426.7   
411   905520         B        11.04         16.83           70.92      373.2   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
78            0.1286           0.34540         0.37540              0.16040   
484           0.1043           0.12990         0.11910              0.06211   
349           0.1158           0.12060         0.01171              0.01787   
411           0.1077           0.07804         0.03046              0.02480   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
78   ...          31.72           170.30      1623.0            0.1639   
484  ...          14.20           112.50       854.3            0.1541   
349  ...          17.72            83.09       496.2            0.1293   
411  ...          26.44            79.93       471.4            0.1369   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
78              0.6164          0.76810               0.25080          0.5440   
484             0.2979          0.40040               0.14520          0.2557   
349             0.1885          0.03122               0.04766          0.3124   
411             0.1482          0.10670               0.07431          0.2998   

     fractal_dimension_worst  Unnamed: 32  
78                   0.09964          NaN  
484                  0.08181          NaN  
349                  0.07590          NaN  
411                  0.07881          NaN  

[4 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [6]:
df.drop(columns=['Unnamed: 32','id'],inplace=True)

In [7]:
df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [8]:
df.isna().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [9]:
df.sample(5)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
138         M        14.95         17.57           96.85      678.1   
115         B        11.93         21.53           76.53      438.6   
162         M        19.59         18.15          130.70     1214.0   
47          M        13.17         18.66           85.98      534.6   
240         B        13.64         15.60           87.38      575.3   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
138          0.11670           0.13050         0.15390              0.08624   
115          0.09768           0.07849         0.03328              0.02008   
162          0.11200           0.16660         0.25080              0.12860   
47           0.11580           0.12310         0.12260              0.07340   
240          0.09423           0.06630         0.04705              0.03731   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
138         0.1957  ...         18.55          21.43           121.40   
115         0.1688  ...         13.67          26.15            87.54   
162         0.2027  ...         26.73          26.39           174.90   
47          0.2128  ...         15.67          27.95           102.80   
240         0.1717  ...         14.85          19.05            94.11   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
138       971.4            0.1411             0.2164           0.3355   
115       583.0            0.1500             0.2399           0.1503   
162      2232.0            0.1438             0.3846           0.6810   
47        759.4            0.1786             0.4166           0.5006   
240       683.4            0.1278             0.1291           0.1533   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
138               0.16670          0.3414                  0.07147  
115               0.07247          0.2438                  0.08541  
162               0.22470          0.3643                  0.09223  
47                0.20880          0.3900                  0.11790  
240               0.09222          0.2530                  0.06510  

[5 rows x 31 columns]

In [10]:
# Encode diagnosis column: M=1, B=0
df['diagnosis'] = df['diagnosis'].map({'M': 1, 'B': 0})


In [11]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          1        17.99         10.38          122.80     1001.0   
1          1        20.57         17.77          132.90     1326.0   
2          1        19.69         21.25          130.00     1203.0   
3          1        11.42         20.38           77.58      386.1   
4          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    int64  
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [13]:
df.describe()

diagnosis  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  569.000000   569.000000    569.000000      569.000000   569.000000   
mean     0.372583    14.127292     19.289649       91.969033   654.889104   
std      0.483918     3.524049      4.301036       24.298981   351.914129   
min      0.000000     6.981000      9.710000       43.790000   143.500000   
25%      0.000000    11.700000     16.170000       75.170000   420.300000   
50%      0.000000    13.370000     18.840000       86.240000   551.100000   
75%      1.000000    15.780000     21.800000      104.100000   782.700000   
max      1.000000    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
count     569.000000  ...    569.000000     569.000000       569.000000   
mean        0.181162  ...     16.269190      25.677223       107.261213   
std         0.027414  ...      4.833242       6.146258        33.602542   
min         0.106000  ...      7.930000      12.020000        50.410000   
25%         0.161900  ...     13.010000      21.080000        84.110000   
50%         0.179200  ...     14.970000      25.410000        97.660000   
75%         0.195700  ...     18.790000      29.720000       125.400000   
max         0.304000  ...     36.040000      49.540000       251.200000   

        area_worst  smoothness_worst  compactness_worst  concavity_worst  \
count   569.000000        569.000000         569.000000       569.000000   
mean    880.583128          0.132369           0.254265         0.272188   
std     569.356993          0.022832           0.157336         0.208624   
min     185.200000          0.071170           0.027290         0.000000   
25%     515.300000          0.116600           0.147200         0.114500   
50%     686.500000          0.131300           0.211900         0.226700   
75%    1084.000000          0.146000           0.339100         0.382900   
max    4254.000000          0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  
count            569.000000      569.000000               569.000000  
mean               0.114606        0.290076                 0.083946  
std                0.065732        0.061867                 0.018061  
min                0.000000        0.156500                 0.055040  
25%                0.064930        0.250400                 0.071460  
50%                0.099930        0.282200                 0.080040  
75%                0.161400        0.317900                 0.092080  
max                0.291000        0.663800                 0.207500  

[8 rows x 31 columns]

In [14]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          1        17.99         10.38          122.80     1001.0   
1          1        20.57         17.77          132.90     1326.0   
2          1        19.69         21.25          130.00     1203.0   
3          1        11.42         20.38           77.58      386.1   
4          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [15]:
#converting the target clounm name
df.rename(columns={'diagnosis':'target'},inplace=True)

In [16]:
df.head()

target  radius_mean  texture_mean  perimeter_mean  area_mean  \
0       1        17.99         10.38          122.80     1001.0   
1       1        20.57         17.77          132.90     1326.0   
2       1        19.69         21.25          130.00     1203.0   
3       1        11.42         20.38           77.58      386.1   
4       1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [17]:
# checking the distribution of Target Varibale
df['target'].value_counts()

target
0    357
1    212
Name: count, dtype: int64

In [18]:
#seperating the features and target
X=df.drop(columns='target',axis=1)
y=df.iloc[:,0]

In [19]:
#feature scaling
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X=scaler.fit_transform(X)

X

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.91202749, 0.59846245,
        0.41886396],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.63917526, 0.23358959,
        0.22287813],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.83505155, 0.40370589,
        0.21343303],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.48728522, 0.12872068,
        0.1519087 ],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.91065292, 0.49714173,
        0.45231536],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.25744136,
        0.10068215]])

In [20]:
y

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: target, Length: 569, dtype: int64

In [21]:
#splitting the data into training data and testing data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [22]:
X_train

array([[0.1452506 , 0.26445722, 0.14249188, ..., 0.22333333, 0.26197516,
        0.14167651],
       [0.18074684, 0.41494758, 0.17275931, ..., 0.25721649, 0.27597083,
        0.14154532],
       [0.43348005, 0.174163  , 0.41814664, ..., 0.38797251, 0.23910901,
        0.09891119],
       ...,
       [0.11619102, 0.29117349, 0.11077327, ..., 0.17360825, 0.17524147,
        0.17263545],
       [0.12963226, 0.28779168, 0.11706171, ..., 0.        , 0.06780997,
        0.06919848],
       [0.21434995, 0.4808928 , 0.21235575, ..., 0.33171821, 0.10782574,
        0.21172767]])

In [23]:
X_test

array([[0.30380046, 0.36557322, 0.30993021, ..., 0.704811  , 0.39818648,
        0.36639118],
       [0.29480808, 0.52553263, 0.27855711, ..., 0.20635739, 0.17327025,
        0.08421881],
       [0.33314402, 0.20121745, 0.31649506, ..., 0.28233677, 0.11255667,
        0.07910272],
       ...,
       [0.62468645, 0.33243152, 0.62200263, ..., 0.7467354 , 0.289178  ,
        0.1686344 ],
       [0.5361825 , 0.3676023 , 0.53216778, ..., 0.51890034, 0.29745713,
        0.15472911],
       [0.3814189 , 0.23774095, 0.37965586, ..., 0.34982818, 0.12063868,
        0.19972452]])

In [24]:
y_train

338    0
427    0
406    0
96     0
490    0
      ..
277    1
9      1
359    0
192    0
559    0
Name: target, Length: 455, dtype: int64

In [25]:
y_test

512    1
457    0
439    0
298    0
37     0
      ..
213    1
519    0
432    1
516    1
500    0
Name: target, Length: 114, dtype: int64

In [26]:
#model training
model=LogisticRegression()
model.fit(X_train,y_train)


LogisticRegression()

In [27]:
#model prediction
y_pred=model.predict(X_test)

In [28]:
#model Evaluation
score=accuracy_score(y_test,y_pred)
score

0.9649122807017544

In [29]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[67,  0],
       [ 4, 43]])

In [30]:
#hyper parameter tuning
from sklearn.model_selection import GridSearchCV

In [31]:
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],             # regularization strength
    'penalty': ['l1', 'l2'],                 # regularization type
    'solver': ['liblinear']                  # works with l1 & l2
}


In [32]:
model = LogisticRegression(max_iter=1000)

grid_search = GridSearchCV(estimator=model,
                           param_grid=param_grid,
                           cv=5,             # 5-fold cross-validation
                           scoring='accuracy',
                           n_jobs=-1,
                           verbose=2)


In [33]:
grid_search.fit(X_train, y_train)


Fitting 5 folds for each of 10 candidates, totalling 50 fits


GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=1000), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l1', 'l2'],
                         'solver': ['liblinear']},
             scoring='accuracy', verbose=2)

In [34]:
print("Best Parameters:", grid_search.best_params_)
print("Best Cross-Validation Accuracy:", grid_search.best_score_)


Best Parameters: {'C': 10, 'penalty': 'l1', 'solver': 'liblinear'}
Best Cross-Validation Accuracy: 0.9758241758241759


In [37]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Predict on test set
y_pred = grid_search.best_estimator_.predict(X_test)

# Accuracy
print("Test Accuracy:", accuracy_score(y_test, y_pred))

# Detailed classification report
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Confusion matrix
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Test Accuracy: 0.956140350877193

Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.97      0.96        67
           1       0.96      0.94      0.95        47

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114


Confusion Matrix:
 [[65  2]
 [ 3 44]]


In [39]:
# Final Logistic Regression Model with Best Parameters
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# 1. Build the model with best parameters
logistic_model = LogisticRegression(C=10, penalty='l1', solver='liblinear', max_iter=1000)

# 2. Fit the model on training data
logistic_model.fit(X_train, y_train)

# 3. Predict on test data
y_pred = logistic_model.predict(X_test)

# 4. Evaluate the model
print(" Test Accuracy:", accuracy_score(y_test, y_pred))
print("\n Classification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


 Test Accuracy: 0.956140350877193

 Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.97      0.96        67
           1       0.96      0.94      0.95        47

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114


Confusion Matrix:
 [[65  2]
 [ 3 44]]


In [42]:
import pickle
with open('logistic_model.pkl', 'wb') as file:
    pickle.dump(logistic_model, file)
